name: Compilar APK Roykola Visor

on:
  push:
    branches: [ main ]  # Se activa al subir cambios a la rama principal
  workflow_dispatch:     # Te permite activarlo manualmente desde la web de GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Java JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Dar permisos de ejecución al compilador Gradle
      run: chmod +x ./gradlew
      continue-on-error: true # Por si subiste el proyecto sin el wrapper gradlew

    - name: Compilar APK (Modo Debug)
      run: |
        if [ -f "./gradlew" ]; then
          ./gradlew assembleDebug
        else
          gradle assembleDebug
        fi

    - name: Subir el archivo APK generado
      uses: actions/upload-artifact@v4
      with:
        name: Roykola-Visor-APK
        path: |
          **/build/outputs/apk/debug/*.apk
