name: Compilar APK Roykola Visor

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Descomprimir carpeta de la app
      run: |
        if [ -f "./app.zip" ]; then
          unzip app.zip -d .
          rm app.zip
        fi

    - name: Configurar Java JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Dar permisos de ejecución al compilador Gradle
      run: chmod +x ./gradlew
      continue-on-error: true

    - name: Compilar APK (Modo Debug)
      run: |
        if [ -f "./gradlew" ]; then
          ./gradlew assembleDebug
        else
          gradle assembleDebug
        fi

    - name: Subir el archivo APK generado
      uses: actions/upload-artifact@v4
      with:
        name: Roykola-Visor-APK
        path: |
          **/build/outputs/apk/debug/*.apk
